<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
	</array>
	<key>name</key>
	<string>Unit Test Report</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>"(.*?)"</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'(.*?)'</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|\s+)(JCL|CAS|JES)..[0-9][0-9][0-9][0-9]I.*$</string>
			<key>name</key>
			<string>token.info-token</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|\s+)(JCL|CAS|JES)..[0-9][0-9][0-9][0-9]W.*$</string>
			<key>name</key>
			<string>token.warn-token</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|\s+)(JCL|CAS|JES)..[0-9][0-9][0-9][0-9]S.*$</string>
			<key>name</key>
			<string>token.debug-token emphasis</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|\s+)(JCL|CAS|JES)..[0-9][0-9][0-9][0-9]E.*$</string>
			<key>name</key>
			<string>token.error-token</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\S+@\S+\.\S+</string>
			<key>name</key>
			<string>markup.bold</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0|1]?[0-9]|2[0-3])\:[0-5][0-9](\:[0-5][0-9])?( ?(?i:(a|p)m?))?( ?[+-]?[0-9]*)(?=\s|$)</string>
			<key>name</key>
			<string>constant.numeric.date</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>token.error-token</string>
				</dict>
			</dict>
			<key>comment</key>
			<string> ::.. </string>
			<key>match</key>
			<string>([\:|/])\s+(?i:(failed))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
			</dict>
			<key>comment</key>
			<string> ::.. </string>
			<key>match</key>
			<string>([\:|/])\s+(?i:(errored|error))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>token.info-token</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>info</string>
			<key>match</key>
			<string>([\:|/])\s+(?i:(passed|completed|information|info))</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\*\*\*\*.*)$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\*\-.*\-\*)</string>
			<key>name</key>
			<string>comment.jsysmsg.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\/\/\*.*)$</string>
			<key>name</key>
			<string>comment.jcl.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(---&gt;)</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:Micro Focus COBOL - mfurun Utility|Unit Testing Framework for.*)$</string>
			<key>name</key>
			<string>entity.name.section.markdown heading.1.markdown markup.heading.markdown</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:Runtime error)</string>
			<key>end</key>
			<string>(^ )(?=[a-zA-z0-9])</string>
			<key>name</key>
			<string>source.utreport</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>token.info-token</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:Fixture filename|Test case|Test Run Summary)</string>
			<key>name</key>
			<string>entity.name.section.markdown heading.2.markdown markup.heading.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^  J.*:|^  [a-zA-Z].*:$)</string>
			<key>name</key>
			<string>entity.name.section.markdown heading.3.markdown markup.heading.markdown</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.jcl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jcl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.symbol.jcl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s+[0-9]+\s+)(//[A-Za-z0-9\$\#@\.]*)\s+([a-zA-Z0-9+\-]*)\s(.*)$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^|\s+)([-+]*[0-9 ,\.]+)(?:$|\s+)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:(^Micro Focus COBOL.*$|^Unit Testing Framework for.*$|^Test Run Summary$))</string>
			<key>name</key>
			<string>emphasis</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:(MFUT[a-zA-Z0-9_-]*))</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.utreport</string>
</dict>
</plist>
